### ISSUE TITLE
Please Guide me 

### ISSUE THREAD

**Issue by Debjit0** [Kitsunejasutin/lenovo-ideapad-l340gaming-hackintosh#1]
I tried installing your efi but i couldnt get it booting from oc. can you please help about what image u used..!

**Comment by Kitsunejasutin** [comment]
Follow the tutorial of flash drive creation, after that paste the EFI on the same flash drive

**Comment by Debjit0** [comment]
> Follow the tutorial of flash drive creation, after that pastr the EFI on the same flash drive

Did the same can u provide the link to mac os

**Comment by Kitsunejasutin** [comment]
What do you mean you can't boot to OC?

**Comment by Debjit0** [comment]
> What do you mean you can't boot to OC?

It opens in oc and then its stuck in oc. The installation media isn't working

**Comment by Kitsunejasutin** [comment]
OC? llike the menu?

**Comment by Debjit0** [comment]
> OC? llike the menu?
> 

Yes the menu isn't showing

**Comment by Debjit0** [comment]
> OC? llike the menu?
> 

Stuck at oc watching status as 0

**Comment by Debjit0** [comment]
> OC? llike the menu?

maybe because i have 16gb RAM
u know how to fix dat

**Comment by Debjit0** [comment]
I was only able to install Catalina

**Comment by Debjit0** [comment]
> OC? llike the menu?
> 

Thank you so much for your hardwork. But there's an issue. When I start installing bigsur,the installer works fine. But it gets stuck at "12 mins remaining" and then apple boot loop occurs.
Can u please help

**Comment by Debjit0** [comment]
> OC? llike the menu?
> 

From where did you download the bigsur file?

**Comment by Kitsunejasutin** [comment]
Using the tutorial that is given by opencore, please review the tutorial again.

**Comment by Debjit0** [comment]
> Using the tutorial that is given by opencore, please review the tutorial again.

Hey, thank you so much for your hard work. I have successfully done it. 
 But there is one more problem. 😅 Can you help mein disabling the dGPU. I now not even getting 1hrs of battery..!

**Comment by Kitsunejasutin** [comment]
It's already disabled

**Comment by farhannovan** [comment]
what version of opencore are you using?

**Comment by Kitsunejasutin** [comment]
https://github.com/Kitsunejasutin/lenovo-ideapad-l340gaming-hackintosh/commit/c895a504c7722b91eb2d8bbab7e872491215f434
I just updated it to 0.7.8 Release
