### ISSUE TITLE
Big Sur Wifi isn't working do you have a fix?

### ISSUE THREAD

**Issue by Debjit0** [Kitsunejasutin/lenovo-ideapad-l340gaming-hackintosh#2]

**Comment by Debjit0** [comment]
can u please share your earlier efi

**Comment by Kitsunejasutin** [comment]
kindly remove the kexts for AirportItlwm and download the BigSur kext [here](https://github.com/OpenIntelWireless/itlwm/releases/download/v2.1.0/AirportItlwm_v2.1.0_stable_BigSur.kext.zip)

**Comment by renatofreireda** [comment]
Great! now i have to try to fix Trackpad and Bluetooth still not working. Have you tried to configure the video card GTX1050 through the OC Legacy Patcher?
